---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_user: vagrant
      ansible_become_password: ""  # optional, for passwordless sudo
      ansible_ssh_private_key_file: ./vagrant/.vagrant/machines/control/virtualbox/private_key

appservers:
  hosts:
    appserver-vm:
      ansible_host: appserver
    frontserver:
      ansible_host: frontserver
      
dbservers:
  hosts:
    dbserver-vm:
      ansible_host: dbserver
      
dockerservers:
  hosts:
    dockerserver:
      ansible_host: dockerserver

jenkinsservers:
  hosts:
    jenkinsserver:
      ansible_host: jenkinsserver
      


