Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  #config.hostmanager.enabled = true
  #config.hostmanager.manage_host = true
  #config.hostmanager.manage_guest = true

  config.vm.define "control", primary: true do |h|
    h.vm.hostname = "control"
    h.vm.network "private_network", ip: "192.168.56.10"
    h.vm.provision "shell", path: "scripts/key.sh"
  end

  config.vm.define "appserver" do |h|
    h.vm.hostname = "appserver"
    h.vm.network "private_network", ip: "192.168.56.101"
    h.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "frontserver" do |h|
    h.vm.hostname = "frontserver"
    h.vm.network "private_network", ip: "192.168.56.103"
    h.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    h.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "dbserver" do |h|
    h.vm.hostname = "dbserver"
    h.vm.network "private_network", ip: "192.168.56.102"
    h.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "dockerserver" do |h|
    h.vm.hostname = "dockerserver"
    h.vm.network "private_network", ip: "192.168.56.110"
    h.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # ✅ Jenkins VM μέσα στο block
  config.vm.define "jenkinsserver" do |h|
    h.vm.hostname = "jenkinsserver"
    h.vm.network "private_network", ip: "192.168.56.120"
    h.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    h.vm.provision "shell", inline: <<-SHELL
      cat /vagrant/control.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
